yaw: 70

x: -5

y: -8

resolution: 18

maximumIterations: 100

stepSize: 0.5

transformationEpsilon: 0.01

euclideanFitnessEpsilon: 0.01

maxCorrespondenceDistance: 2

fitnessScore: 3

yaw_thre: 0.5

test1File: src/perception/src/test1.pcd

test2File: src/perception/src/test2.pcd

# test1File: src/perception/src/4_whole.pcd

# test2File: src/perception/src/4_whole.pcd

yaw_pre: 0

x_pre: 0

y_pre: 0

menu_bool: n
